<?php
/**
 * Created by PhpStorm.
 * User: Anjali
 * Date: 02-06-2021
 * Time: 20:34
 */
        ?>
<body bgcolor="#ffe4c4">
<h2 style="color: red">Privacy Policy for Website</h2>
<p>
    Effective Date:April 15th, 2021
</p>
<br/>
Applicable To theFollowing Website: www.onecliq.com
<br/>
Article 1 - DEFINITIONS:
<br/>
a) APPLICABLE WEBSITE: ThisPrivacy Policy will refer to and be applicable to the Website listed above,which shall hereinafter be referred to as "Website." Any listedWebsite may also refer to a corresponding mobile application, should one becurrently in use or hereinafter developed.
<br/>
b) EFFECTIVE DATE: "EffectiveDate" means the date this Privacy Policy comes into force and effect.
<br/>
c) PARTIES: The parties to thisprivacy policy are the following data controller: Spyro Digital Private Limited("Data Controller") and you, as the user of this Website.Hereinafter, the parties will individually be referred to as "Party"and collectively as "Parties."
<br/>
d) DATA CONTROLLER: DataController is the publisher, owner, and operator of the Website and is theParty responsible for the collection of information described herein. DataController shall be referred to either by Data Controller's name or "DataController," as listed above. If Data Controller or Data Controller'sproperty shall be referred to through first-person pronouns, it shall be throughthe use of the following: us, we, our, ours, etc.
<br/>
e) YOU: Should you agree to thisPrivacy Policy and continue your use of the Website, you will be referred toherein as either you, the user, or if any second-person pronouns are requiredand applicable, such pronouns as 'your", "yours", etc.
<br/>
f) GOODS: "Goods" meansany goods that we make available for sale on the Website.
<br/>
g) PERSONAL DATA: "PersonalDATA" means personal data and information that we obtain from you inconnection with your use of the Website which is capable of identifying you inany manner.
<br/>
Article 2 - GENERAL INFORMATION:
<br/>
This privacy policy (hereinafter"Privacy Policy") describes how we collect and use the Personal Datathat we receive about you, as well as your rights in relation to that PersonalData, when you visit our Website or purchase our Goods.
<br/>
This Privacy Policy does not coverany information that we may receive about you through sources other than theuse of our Website. The Website may link out to other websites or mobileapplications, but this Privacy Policy does not and will not apply to any ofthose linked websites or applications.
<br/>
We are committed to the protectionof your privacy while you use our Website.
<br/>
By continuing to use our Website,you acknowledge that you have had the chance to review and consider thisPrivacy Policy, and you acknowledge that you agree to it. This means that youalso consent to the use of your information and the method of disclosure asdescribed in this Privacy Policy. If you do not understand the Privacy Policyor do not agree to it then you agree to immediately cease your use of ourWebsite.
<br/>
Article 3 -CONTACT:
<br/>
The Party responsible for theprocessing of your personal data is as follows: Spyro Digital Private Limited.The Data Controller may be contacted as follows:
<br/>
2/587/26, New 50/859/28, 2ndFloor, United Towers, Laloor Road, Aranattukara, Thrissur-680611
<br/>
The Data Controller and operatorof the Website are one and the same.
<br/>
Article 4 - RULES:
<br/>
This Privacy Policy (“Policy“) is published in accordance with the provisionsof Rule 3(1) of the Information Technology (Intermediaries Guidelines) Rules,2011. The Policy is an ‘electronic record’ as contemplated under section 2(t)of the Information Technology Act, 2000 and the rules. This Policy beingan electronic record is generated by a computer system and does not require anyphysical or digital signature.
<br/>
Article 5 - MODIFICATIONS ANDREVISIONS:
<br/>
We reserve the right to modify,revise, or otherwise amend this Privacy Policy at any time and in any manner.If we do so, however, we will notify you and obtain your consent to the changein processing. Unless we specifically obtain your consent, any changes to thePrivacy Policy will only impact the information collected on or after the dateof the change. It is also your responsibility to periodically check this pagefor any such modification, revision or amendment.
<br/>

Article 6 - THE PERSONAL DATA WE RECEIVE FROM YOU:
<br/>
Depending on how you use ourWebsite, you will be subject to different types of Personal Data collected anddifferent manners of collection:
<br/>
a) Registeredusers: You, as a user of the Website, may be asked to register in order touse the Website or to purchase the Goods available for sale.
<br/>
During the process of yourregistration, we will collect some of the following Personal Data from youthrough your voluntary disclosure:
<br/>
Name, Mobile Number, Gender
<br/>
Personal Data may be asked for inrelation to:
<br/>
I) Interaction with ourrepresentatives in any way
<br/>
II) making purchases
<br/>
III) receiving notifications bytext message or email about marketing
<br/>
IV) receiving general emails fromus
<br/>
V) commenting on our content orother user-generated content on our Website, such as blogs, articles,photographs or videos, or participating in our forums, bulletin boards, chatrooms or other similar features

By undergoing the registrationprocess, you consent to us collecting your Personal Data, including thePersonal Data described in this clause, as well as storing, using or disclosingyour Personal Data in accordance with this Privacy Policy.
<br/>
b) Unregisteredusers: If you are a passive user of the Website and do not register for anypurchases or other service, you may still be subject to certain passive datacollection ("Passive Data Collection"). Such Passive Data Collectionmay include through cookies, as described below, IP address information,location information, and certain browser data, such as history and/or sessioninformation.
<br/>
c) Allusers: The Passive Data Collection which applies to Unregistered usersshall also apply to all other users and/or visitors of our Website.
<br/>
d) Sales& Billing Information: In order to purchase any of the goods on theWebsite, you will be asked to provide certain credit information, billingaddress information, and possibly additional specific information so that youmay be properly charged for your purchases. This payment and billinginformation may be stored for the following period: 3 month. If so, it will beused exclusively to assist you with making future purchases with us.
<br/>
e) RelatedEntities: We may share your Personal Data, including Personal Data thatidentifies you personally, with any of our parent companies, subsidiarycompanies, affiliates or other trusted related entities.
<br/>
However, we only share yourPersonal Data with a trusted related entity if that entity agrees to ourprivacy standards as set out in this Privacy Policy and to treat your PersonalData in the same manner that we do.
<br/>
f) EmailMarketing: You may be asked to provide certain Personal Data, such as yourname and email address, for the purpose of receiving email marketingcommunications. This information will only be obtained through your voluntarydisclosure and you will be asked to affirmatively opt-in to email marketingcommunications.
<br/>
g) UserExperience: From time to time we may request information from you to assistus in improving our Website, and the Goods we sell, such as demographicinformation or your particular preferences.
<br/>
h) ContentInteraction: Our Website may allow you to comment on the content that weprovide or the content that other users provide, such as blogs, multimedia, orforum posts. If so, we may collect some Personal Data from you at that time,such as, but not limited to, username or email address.
<br/>
i) Combinedor Aggregated Information: We may combine or aggregate some of yourPersonal Data in order to better serve you and to better enhance and update ourWebsite for your and other consumers' use.
<br/>
We may also share such aggregatedinformation with others, but only if that aggregated information does notcontain any Personal Data.
<br/>
Article 7 - THE PERSONAL DATA WERECEIVE AUTOMATICALLY:
<br/>
Cookies: Wemay collect information from you through automatic tracking systems (such asinformation about your browsing preferences) as well as through informationthat you volunteer to us (such as information that you provide during aregistration process or at other times while using the Website, as describedabove).
<br/>
For example, we use cookies tomake your browsing experience easier and more intuitive: cookies are smallstrings of text used to store some information that may concern the user, hisor her preferences or the device they are using to access the Internet (such asa computer, tablet, or mobile phone). Cookies are mainly used to adapt theoperation of the site to your expectations, offering a more personalizedbrowsing experience and memorizing the choices you made previously.

A cookie consists of a reduced setof data transferred to your browser from a web server and it can only be readby the server that made the transfer. This is not executable code and does nottransmit viruses.

Cookies do not record or store anyPersonal Data. If you want, you can prevent the use of cookies, but then youmay not be able to use our Website as we intend. To proceed without changingthe options related to cookies, simply continue to use our Website.

Technicalcookies: Technical cookies, which can also sometimes be calledHTML cookies, are used for navigation and to facilitate your access to and useof the site. They are necessary for the transmission of communications on thenetwork or to supply services requested by you. The use of technical cookiesallows the safe and efficient use of the site.

You can manage or request thegeneral deactivation or cancelation of cookies through your browser. If you dothis though, please be advised this action might slow down or prevent access tosome parts of the site.

Cookies may also be retransmittedby an analytics or statistics provider to collect aggregated information on thenumber of users and how they visit the Website. These are also consideredtechnical cookies when they operate as described.

Temporary session cookies aredeleted automatically at the end of the browsing session - these are mostlyused to identify you and ensure that you don't have to log in each time -whereas permanent cookies remain active longer than just one particularsession.

Third-partycookies: We may also utilize third-party cookies, which arecookies sent by a third-party to your computer. Permanent cookies are oftenthird-party cookies. The majority of third-party cookies consist of trackingcookies used to identify online behavior, understand interests and thencustomize advertising for users.

Third-party analytical cookies mayalso be installed. They are sent from the domains of the aforementioned thirdparties external to the site. Third-party analytical cookies are used to detectinformation on user behavior on our Website. This place anonymously, in orderto monitor the performance and improve the usability of the site. Third-partyprofiling cookies are used to create profiles relating to users, in order topropose advertising in line with the choices expressed by the users themselves.

Profilingcookies: We may also use profiling cookies, which are those thatcreate profiles related to the user and are used in order to send advertisingto the user's browser.

When these types of cookies areused, we will receive your explicit consent.
<br/>
Support inconfiguring your browser: You can manage cookie through thesettings of your browser on your device. However, deleting cookies from yourbrowser may remove the preferences you have set for this Website.
<br/>
For further information andsupport, you can also visit the specific help page of the web browser you areusing:
<br/>
- Internet Explorer:http://windows.microsoft.com/en-us/windows-vista/block-or-allow-cookies
<br/>
- Firefox:https://support.mozilla.org/en-us/kb/enable-and-disable-cookies-website-preferences
<br/>
- Safari:http://www.apple.com/legal/privacy/
<br/>
- Chrome:https://support.google.com/accounts/answer/61416?hl=en
<br/>
- Opera: http://www.opera.com/help/tutorials/security/cookies/
<br/>
Log Data: Likeall websites and mobile applications, this Website also makes use of log fileswhich store automatic information collected during user visits. The differenttypes of log data could be as follows:
<br/>
- internet protocol (IP) address;<br/>
- type of browser and device parameters used to connect to the Website;<br/>
- name of the Internet Service Provider (ISP);<br/>
- date and time of visit;<br/>
- web page of origin of the user (referral) and exit;<br/>
- possibly the number of clicks.<br/>

The aforementioned information isprocessed in an automated form and collected in an exclusively aggregatedmanner in order to verify the correct functioning of the site, and for securityreasons. This information will be processed according to the legitimateinterests of the Data Controller.
<br/>
For security purposes (spamfilters, firewalls, virus detection), the automatically recorded data may alsopossibly include Personal Data such as IP address, which could be used, inaccordance with applicable laws, in order to block attempts at damage to theWebsite or damage to other users, or in the case of harmful activities orcrime. Such data are never used for the identification or profiling of theuser, but only for the protection of the Website and our users. Suchinformation will be treated according to the legitimate interests of the DataController.
<br/>
Article 8 - THIRD PARTIES:
<br/>
We may utilize third party serviceproviders ("Third Party Service Providers"), from time to time or allthe time, to help us with our Website, and to help serve you.
<br/>
We may use Third Party ServiceProviders to assist with information storage (such as cloud storage).
<br/>
We may provide some of yourPersonal Data to Third Party Service Providers in order to help us track usagedata, such as referral websites, dates and times of page requests, etc. We usethis information to understand patterns of usage of, and to improve, theWebsite.
<br/>
We may use Third Party ServiceProviders to host the Website. In this instance, the Third Party ServiceProvider will have access to your Personal Data.
<br/>
We may use Third Party ServiceProviders to fulfill orders in relation to the Website.
<br/>
We may allow third parties toadvertise on the Website. These third parties may use cookies in connection withtheir advertisements (see the "Cookies" clause in this PrivacyPolicy).
<br/>
Some of our Third Party ServiceProviders may be located outside of the India and may not be subject to Indiaprivacy laws. The countries or regions in which our Third Party Service Providersmay be located include:
<br/>
We only share your Personal Datawith a Third Party Service Provider if that provider agrees to our privacystandards as set out in this Privacy Policy.
<br/>
Your Personal Data will not besold or otherwise transferred to other third parties without your approval.
<br/>
Notwithstanding the otherprovisions of this Privacy Policy, we may provide your Personal Data to a thirdparty or to third parties in order to protect the rights, property or safety,of us, our customers or third parties, or as otherwise required by law.
<br/>
We will not knowingly share yourPersonal Data with any third parties other than in accordance with this PrivacyPolicy.
<br/>
If your Personal Data might beprovided to a third party in a manner which is other than as explained in thisPrivacy Policy, you will be notified. You will also have the opportunity torequest that we not share that information.
<br/>
Article 9 - SOCIAL NETWORKPLUGINS:
<br/>
This Website incorporates plug-inand/or buttons for social networks, in order to allow easy sharing of contenton your favorite social networks. These plug-in are programmed so as not to setany cookies when accessing the page, to safeguard the privacy of users. Cookiesmay be set, however, if you make voluntary use of the plug-in. Please note thatif you browse while being logged into the social network then you have alreadyconsented to the use of cookies conveyed through this Website at the time thatyou registered with the particular social network.
<br/>
The collection and use ofinformation obtained by means of the plug-in are governed by the respectiveprivacy policies of the social networks, which can be found below:
<br/>
Face book:https://www.facebook.com/help/cookies
<br/>
Twitter:https://help.twitter.com/en/rules-and-policies/twitter-cookies
<br/>
Google+: http://www.google.com/policies/technologies/cookies
<br/>
Interest:https://about.pinterest.com/it/privacy-policy
<br/>
Whatsapp: http://www.whatsapp.com/privacy/privacy-policy
<br/>
LinkedIn:https://www.linkedin.com/legal/cookie-policy
<br/>
Article 10 - HOW PERSONAL DATA ISSTORED:
<br/>
We use secure physical and digitalsystems to store your Personal Data when appropriate. We ensure that yourPersonal Data is protected against unauthorized access, disclosure, ordestructions.
<br/>
Please note, however, that nosystem involving the transmission of information via the internet, or theelectronic storage of data, is completely secure. However, we take theprotection and storage of your Personal Data very seriously. We take allreasonable steps to protect your Personal Data.
<br/>
Personal Data is stored throughoutyour relationship with us. We delete your Personal Data upon request forcancelation of your account or other general request for the deletion of data.
<br/>
In the event of a breach of yourPersonal Data, you will be notified in a reasonable time frame, but in no eventlater than two weeks, and we will follow all applicable laws regarding suchbreach.
<br/>
Article 11 - PURPOSES OFPROCESSING OF PERSONAL DATA:
<br/>
We primarily use your PersonalData to help us provide a better experience for you on our Website and toprovide you the services and/or information you may have requested, such as useof our Website.
<br/>
Information that does not identifyyou personally, but that may assist in providing us broad overviews of ourcustomer base, will be used for market research or marketing efforts. Suchinformation may include, but is not limited to, interests based on yourcookies.
<br/>
Personal Data that may beconsidering identifying may be used for the following:
<br/>
a) Improving your personal userexperience
<br/>
b) Communicating with you aboutyour user account with us
<br/>
c) Marketing and advertising toyou, including via email
<br/>
d) Fulfilling your purchases
<br/>
e) Providing customer service toyou
<br/>
f) Advising you about updates tothe Website or related Items
<br/>
Article 12 - DISCLOSURE OFPERSONAL DATA:
<br/>
Although our policy is to maintainthe privacy of your Personal Data as described herein, we may disclose yourPersonal Data if we believe that it is reasonable to do so in certain cases, inour sole and exclusive discretion. Such cases may include, but are not limitedto:
<br/>
a) To satisfy any local, state, orgovernment laws or regulations
<br/>
b) To respond to requests, suchdiscovery, criminal, civil, or administrative process, court orders, or writsfrom law enforcement or other governmental or legal bodies
<br/>
c) To bring legal action against auser who has violated the law or violated the terms of use of our Website
<br/>
d) As may be necessary for theoperation of our Website
<br/>
e) To generally cooperate with anylawful investigation about our users
<br/>
f) If we suspect any fraudulentactivity on our Website or if we have noticed any activity which may violateour terms or other applicable rules
<br/>
Article 13 - PUBLICINFORMATION:
<br/>
We may allow users to post theirown content or information publicly on our Website. Such content or informationmay include, but is not limited to, photographs, status updates, blogs,articles, or other personal snippets. Please be aware that any such informationor content maybe that you post ought to be considered entirely public and thatwe do not purport to maintain the privacy of such public information.
<br/>
Article 14 - OPTING OUT OFTRANSMITTALS FROM US:
<br/>
From time to time, we may send youinformational or marketing communications related to our Website such asannouncements or other information. If you wish to opt-out of suchcommunications, you may contact the following email: info@dailycliq.com. Youmay also click the opt-out link which will be provided at the bottom of any andall such communications.
<br/>
Please be advised that even thoughyou may opt-out of such communications, you may still receive information fromus that is specifically about your use of our Website or about your accountwith us.
<br/>
By providing any Personal Data tous, or by using our Website in any manner, you have created a commercialrelationship with us. As such, you agree that any email sent from us orthird-party affiliates, even unsolicited email, shall specifically not beconsidered SPAM, as that term is legally defined.
<br/>
Article 15 - MODIFYING, DELETING,AND ACCESSING YOUR INFORMATION:
<br/>
If you wish to modify or deleteany information we may have about you, or you wish to simply access anyinformation we have about you, you may do so from your account settings page.
<br/>
Article 16 - ACCEPTANCE OF RISK:
<br/>
By continuing to our Website inany manner, use the Product, you manifest your continuing asset to this PrivacyPolicy. You further acknowledge, agree and accept that no transmission ofinformation or data via the internet is not always completely secure, no matterwhat steps are taken. You acknowledge, agree and accept that we do notguarantee or warrant the security of any information that you provide to us,and that you transmit such information at your own risk.

<br/>
Article 17 - YOUR RIGHTS:

You have many rights in relationto your Personal Data. Specifically, your rights are as follows:
<br/>
- The right to be informed aboutthe processing of your Personal Data
<br/>
- The right to have access to yourPersonal Data
<br/>

- The right to update and/orcorrect your Personal Data
<br/>
- The right to portability of yourPersonal Data
<br/>
- The right to oppose or limit theprocessing of your Personal Data
<br/>
- The right to request that westop processing and delete your Personal Data
<br/>
- The right to block any PersonalData processing in violation of any applicable law
<br/>
- The right to launch a complaint withthe applicable data protection authority in another jurisdiction
<br/>
Such rights can all be exercisedby contacting us at the relevant contact information listed in this PrivacyPolicy.
<br/>
Article 18 - CONTACT INFORMATION:
<br/>
If you have any questions aboutthis Privacy Policy or the way we collect information from you, or if you wouldlike to launch a complaint about anything related to this Privacy Policy, youmay contact us at the following email address: customersupport@dailycliq.com.
<br/>
Article 19 – GOVERNMENT LAW ANDJURISDICTION:

<br/>

The terms and conditions of this Policy shall begoverned by Indian Law and the judiciary courts in Thrissur, Kerala shall onlyhave exclusive jurisdiction to resolve any disputes.
<br/>
</body>

